###################################################################

server:
  address: 0.0.0.0
  port: ${PORT:8888}

spring:
  application:
    name: metadata-service

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:16570/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:eaXtdvmmNvEkfyuSqwRsBUGlPqXGPAIN}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  cache:
    type: none

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: https://microservice-6dyb.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

metadata:
  key:
    pattern: "^[a-zA-Z_][a-zA-Z0-9_.]*$"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false