
###################################################################

server:
  address: 0.0.0.0
  port: ${PORT:8763}

spring:
  application:
    name: metadata-service
  data:
    redis:
      url: redis://default:ItRBEjljWMXDHICNFJdCxBTjGIHPmzMk@centerbeam.proxy.rlwy.net:25969



  #datasource:
  #  url: jdbc:mysql://ballast.proxy.rlwy.net:37143/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #  username: root
  #  password: ${DB_PASSWORD:usWWjahOWNcwHppqrsESYhBVXplBvJDI}
  #  driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa:
  #  database-platform: org.hibernate.dialect.MySQL8Dialect
  #  hibernate:
  #    ddl-auto: update
  #  show-sql: true
  #  properties:
  #   hibernate:
  #     format_sql: true
  #      jdbc:
  #       time_zone: UTC

  cache:
    type: none

  datasource:
    url: jdbc:mysql://shinkansen.proxy.rlwy.net:39756/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:pNXyuMURcClGkORjMGPzkfZezcuwjhkj}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # JPA / Hibernate settings (adjust as needed)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx9kqCNTmQc3NKpkTizMn6N4X4AuHUqFhtPzoHccV6MiNnsD7UGsiYPp/Ifn/4TqqnJFhSI/a+UhtWY2zhOcToeekEx/hCcgTUeKBwFuhWlXKjvR5Ao7Qezkf86DQ3GsM1k+vKOQ26Mfa8iksmGlIYotL/ALAPKdwsVq9f95L1iDFB7/CUTSEfOhD0WdUkmLae/Ta/sHa0qz4ZdoN/dKvqkepNk1P1hGM86YBvCLca72wRtJe7BsoF+oz2CQ73x+1Xc/6MZ8jProFO4L8BBU6fJzWX/sXDSgjU8nt8Y1tClzhlB60MUtjaXFAyq8ltpiS2OGK2zSZnNjkQ83lKxyC0QIDAQAB
      -----END PUBLIC KEY-----

eureka:
  client:
    service-url:
      defaultZone: https://microservice-59zl.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false

    instance-id: metadata-service:${random.value}

    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 443


metadata:
  key:
    pattern: "^[a-zA-Z_][a-zA-Z0-9_.]*$"
  


management:
  endpoints:
    web:
      exposure:
        include: health,info