server:
  address: 0.0.0.0
  port: ${PORT:8123}

spring:
  application:
    name: metadata-service

  data:
    redis:
      url: ${REDIS_URL}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
      fetch-registry: true
      register-with-eureka: true

metadata:
  key:
    pattern: ${METADATA_KEY_PATTERN}